### PR TITLE
#80 rte buttons not working

### PR DESCRIPTION
**Pull request by dawoe**
Fixes issue #80 

Uses umb-overlay directive for showing dialog instead of dialog service.
Because of this minimum Umbraco version is now 7.4

### CODE REVIEW

**Comment by leekelleher** [comment]
Thank you @dawoe!  I've taken a quick glance at the changes - looks good to me.
I've assigned @mattbrailsford for a review of it too.

re: branches - I've re-targeted this PR to the `develop` branch, otherwise merging with `master` will mess up our release strategy.

**Comment by dawoe** [comment]
Hi @leekelleher and @mattbrailsford 

I merged in the develop branch. Locally it builds fine. But there is something wrong with the app veyor build. But I see that happening on the latest commit on develop as well

Dave

**Comment by leekelleher** [comment]
I'll take a look at why the `develop` branch is failing on AppVeyor 👍

**Comment by dawoe** [comment]
Seems to be the restoring of nuget packages

**Comment by dawoe** [comment]
If i'm needed will be available again tonight. Now I'm off the visit my godchild that was born yesterday evening 👶 🍼

**Comment by leekelleher** [comment]
Turns out that we had an older version of NuGet.exe (v2), which is no longer supported, NuGet requires v3.2+ ... I've upgraded our solution to use NuGet.exe v4.4.

**Comment by mattbrailsford** [comment]
Happy to merge once the build is fixed

**Comment by dawoe** [comment]
Merged in latest develop branch. Now the appveyor build is working

**Comment by leekelleher** [comment]
Merged! Thanks @dawoe 🎉 #h5yr

**Comment by dawoe** [comment]
Any idea when this will be released ?

**Comment by leekelleher** [comment]
@dawoe It wont be today 😅 - I'll chat with @mattbrailsford to schedule it in.

**Comment by TimGeyssens** [comment]
Any eta on the next v with this fix in it? Thanks 😄

**Comment by dawoe** [comment]
Hi @TimGeyssens ,

You can get the nuget beta version here : https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.DocTypeGridEditor

If you prefer the umbraco package you can get that here : https://ci.appveyor.com/project/UMCO/umbraco-doc-type-grid-editor/build/artifacts

**Comment by leekelleher** [comment]
We haven't got an ETA yet, _(hopefully soon - I'm juggling projects)_.

In the meantime, the build packages are available on AppVeyor: <https://ci.appveyor.com/project/UMCO/umbraco-doc-type-grid-editor/build/artifacts>
...and there's a MyGet feed for Umbraco Community Packages: <https://www.myget.org/gallery/umbraco-packages>

**Comment by TimGeyssens** [comment]
Beta is fine for now, thanks for the quick reply!

**Comment by MartijnKooij** [comment]
Any breaking changes in this alpha? I tried it to see if it would fix our issue (#92) as well but if I don't make any changes, just install the package zip. The sidebar just breaks, if I choose our custom editor the screen flickers but nothing shows.

This is our current config in case it helps.
```
{
"gridEditors": [
  {
    "name": "Accordion",
    "alias": "pggm.accordion",
    "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
    "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
    "icon": "icon-list color-green",
    "config": {
      "allowedDocTypes": ["accordionDoctype"],
      "nameTemplate": "accordion",
      "enablePreview": true,
      "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
      "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor"
    }
  }
  ]
}
```

**Pull request merged**
